language: php

cache:
  directories:
    - bin
    - vendor
    - $HOME/.composer/cache

php:
  - 5.6
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - bin/phpspec run -f pretty
