imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

sylius_bot_crowdin:
    project:
        base:
            organization: SyliusBot
