imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

#jjanvier_crowdin:
#    crowdin:
#        api_key: %crowdin_api_key%
#        project_identifier: %crowdin_project_identifier%
#    project:
#        path: sources
#    archive:
#        clean: true
#        header: "# This file is part of the Sylius package.\n# (c) Paweł Jędrzejewski\n\n"
#    git:
#        commit_message: "[ci skip] Updating translations from Crowdin"
#    github:
#        username: SyliusBot
#        email: bot@sylius.org
#        token: %github_token%
#        organization: Sylius
#        project: Sylius
#        origin_branch: master
#        pr_title: "[CrowdIn] Auto-updated translations"

sylius_bot_crowdin:
    crowdin:
        git:
            message: "[Translations] Updated translations from Crowdin"
        translation_header: "# This file is part of the Sylius package.\n# (c) Paweł Jędrzejewski\n\n"
        project_id: sylius
        api_key: %crowdin_api_key%
    github:
        authorization_token: %github_authorization_token%
    project:
        base:
            organization: Sylius
            repository: Sylius
        head:
            organization: SyliusBot
            repository: Sylius
            branch: crowdin-translations
        locale_replacements:
            es_ES: es
            sv_SE: sv
            pt_PT: pt
